baseURL = "/"
languageCode = "en-us"
title = "Adventures Preschool"
theme = "educenter"
summaryLength = 10
[pagination]
pagerSize = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Plugins
[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/animate/animate.css"
  [[params.plugins.css]]
  link = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  link = "https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
  [[params.plugins.css]]
  link = "css/custom-preschool.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  link = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  link = "https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"
  [[params.plugins.js]]
  link = "js/swiper-init.js"

[params]
  logo = "images/logos/adventures-logo-combined.png"
  # Meta data
  description = "Adventures Preschool - Where children learn by being actively engaged, by playing, and by experiencing"
  author = "Adventures Preschool"
  # contact info
  address = "2622 Lincoln Way, Ames, Iowa"
  mobile = "515-292-1736"
  email = "info@adventurespreschool.org"
  # contact form action
  contact_form_action = "#" # contact form works with https://formspree.io
  # Google Analitycs
  google_analitycs_id = "" # your id
  # top header
  top_header = true

  # Preloader
  [params.preloader]
  enable = false
  preloader = "images/logos/adventures-logo.png" # use jpg, png, svg or gif format.

  # Subscription
  [params.subscription]
  enable = false
  # mailchimp subsciption
  mailchimp_form_action = "" # replace this url with yours
  mailchimp_form_name = "" # replace this code with yours

  # # google map
  # [params.map]
  # enable = true
  # gmap_api = "https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&region=US"
  # map_latitude = "42.0307"
  # map_longitude = "-93.6319"
  # map_marker = "images/marker.png"

  # cookies
  [params.cookies]
  enable = false
  expire_days = 2

  ############################# social site ########################
  [[params.social]]
  title = "facebook"
  icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
  link = "https://www.facebook.com/adventurespreschool"

############################ English Navigation ###############
[[menu.main]]
  name = "Enroll"
  weight = 1
  [[menu.main]]
  parent = "Enroll"
  name = "School Year Program"
  url = "enroll/school-year-program/"
  weight = 1

  # [[menu.main]]
  # parent = "Enroll"
  # name = "Summer Camp"
  # url = "enroll/summer-camp/"
  # weight = 2

[[menu.main]]
  name = "Certifications"
  weight = 2
  hasChildren = true

  [[menu.main]]
  parent = "Certifications"
  name = "Nature Explore"
  url = "certifications/nature-explore/"

  [[menu.main]]
  parent = "Certifications"
  name = "IQ4K"
  url = "certifications/iq4k/"

  [[menu.main]]
  parent = "Certifications"
  name = "Iowa HHS"
  url = "certifications/iowa-hhs/"

# main menu
[[menu.main]]
  name = "Resources"
  weight = 3

  [[menu.main]]
  parent = "Resources"
  name = "About Us"
  url = "resources/about/"
  weight = 1

  [[menu.main]]
  parent = "Resources"
  name = "Philosophy"
  url = "resources/philosophy/"
  weight = 2

  [[menu.main]]
    parent = "Resources"
    name = "Teachers"
    url = "teachers/"
    weight = 3

  [[menu.main]]
    parent = "Resources"
    name = "Parents"
    url = "resources/parents/"
    weight = 4

[[menu.main]]
  name = "Contact Us"
  url = "contact/"
  weight = 4

# # footer menu
# [[menu.footer]]
#   name = "teachers"
#   url = "teacher/"

# [[menu.footer]]
#   name = "gallery"
#   url = "gallery/"

# [[menu.footer]]
#   name = "contact"
#   url = "contact/"
